blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/Aqualia/Alph/security/policy
    about: Please review SECURITY.md for responsible disclosure guidelines.
